### ISSUE TITLE
package exports databaseFactory instead of DatabaseFactory, does not export DatabaseInterface

### ISSUE THREAD

**Issue by retorquere** [MockingMagician/promised-db#5]
The package exports databaseFactory instead of DatabaseFactory, does not export DatabaseInterface.

**Comment by MockingMagician** [comment]
Hmmm, do you have any kind of problem during import ?

**Comment by retorquere** [comment]
Yeah if I follow the sample from the main page, the imports (DatabaseFactory and DatabaseInterface) are not found.

**Comment by MockingMagician** [comment]
I had written a generator for my index and it was indeed a mess to say the least. Just re-exporting imports seems to be enough. Sometimes you're looking for something too complicated for the simple things.

Fixed in v3.0.0
