### ISSUE TITLE
objectStore.add should return the object key

### ISSUE THREAD

**Issue by retorquere** [MockingMagician/promised-db#6]
According to [this](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/add):

> If the operation is successful, the value of the request's [result](https://developer.mozilla.org/en-US/docs/Web/API/IDBRequest/result) property is the key for the new record.

it should not return void

**Comment by MockingMagician** [comment]
My choice was completely biased. I was deviating a little from the indexedDB API, but at the same time, why return the value of a key you already know?

The answer: auto-increment, so yes, it's better all the same, thank you!
