### ISSUE TITLE
openCursor on a store with a compound keypath

### ISSUE THREAD

**Issue by retorquere** [MockingMagician/promised-db#8]
If I have a store like

```
db.createObjectStore('BetterBibTeX', { keyPath: [ 'context', 'itemID' ]}),
```

what would I give for the PK type in an `openCursor` call?

**Comment by MockingMagician** [comment]
It depends on what you're storing in context and itemId; for example, if it's a string for context and a number for itemId, then PK should look like `[string,number]`.

Full example:

```ts
await objStore.add({ context: 'bck', itemID: 1, foo: 'bar' })
let cursor = objStore.openCursor<[string,number],[ string,number], {context: string, itemId: number, foo: string}>()
```

PK and K are the same here cause  I'm iterating onto an objsectStore, not an Index
